# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada07ee63f5a193b057f7058e2c65abd4fe10bce68beae38e8487d57026e6215fd2e63d9e4e14e0d9276b493a31553a4df974edc2970efdb7f1e079c02b5dac2

test:
  secret_key_base: ca0d50d7913a044968b2d1c84079a33e8077b4a564b24b2d4e3444e8d7b3d1c468c3dd01184225240c62ada3047db7e0ee64e64a14dd1ba43efc6008b91c9b48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
